language: ruby
rvm:
- 2.1.3
env:
  global:
  - secure: TCBS7/ROBmI3z6tLF9ZpVA9fyy8RCpmnZLa0E349Jj1ZqYRk/A/1KTPfJwgTfcl+t5+Xz61lulS4m7CD0OsKvKU4SGZGrpl//itf2xS9LBCa0r4UxEKxg94BA32+xWa06XNZ1/Ym2SLtdw9D7/sGP2vb7psini+waM+5gs5B6SE=
  - secure: RhvwKL7OKlZBJmH6srZG9HnhOkBJrRjFrGYVjX0+nqswBRzQP62VfQbiO5AJWTnXXiZmdzqejMvpPqHgpK/2thuX/qyUNEVTcOGPHmKzA7JYK8Hv9TE3lGn9doCnLz2Qzj7rB/NuiVuCDbbYC61sviIzK7AERMICxjsejSp6hJ8=
  - secure: ASp04/Vs7eYIVjp97tf6gWDspzNfK7Z9qLKrm5dAXLhllKL5MM+f7dQwUELcw5xSLhrw3F59INgFU4EoIaRSi+QT2J242P2VkURLYuEDPKV+I4P65/OKFkvkixqlgG7NeFPKemVDX8xicRsIKvfVEKDVOHSlhOecqYEpg1BRHN8=
