language: ruby
rvm:
- 2.1.3
env:
  global:
    secure: TCBS7/ROBmI3z6tLF9ZpVA9fyy8RCpmnZLa0E349Jj1ZqYRk/A/1KTPfJwgTfcl+t5+Xz61lulS4m7CD0OsKvKU4SGZGrpl//itf2xS9LBCa0r4UxEKxg94BA32+xWa06XNZ1/Ym2SLtdw9D7/sGP2vb7psini+waM+5gs5B6SE=
